/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CallGlyphs: typeof import('./src/components/Glyphs/CallGlyphs.vue')['default']
    GB: typeof import('./src/components/Glyphs/G-B.vue')['default']
    GCedillaC: typeof import('./src/components/Glyphs/G-cedillaC.vue')['default']
    GCedillaS: typeof import('./src/components/Glyphs/G-cedillaS.vue')['default']
    GComma: typeof import('./src/components/Glyphs/G-comma.vue')['default']
    GD: typeof import('./src/components/Glyphs/G-D.vue')['default']
    GE: typeof import('./src/components/Glyphs/G-E.vue')['default']
    GF: typeof import('./src/components/Glyphs/G-F.vue')['default']
    GG: typeof import('./src/components/Glyphs/G-G.vue')['default']
    GH: typeof import('./src/components/Glyphs/G-H.vue')['default']
    GI: typeof import('./src/components/Glyphs/G-I.vue')['default']
    GJ: typeof import('./src/components/Glyphs/G-J.vue')['default']
    GK: typeof import('./src/components/Glyphs/G-K.vue')['default']
    GL: typeof import('./src/components/Glyphs/G-L.vue')['default']
    GLongdash: typeof import('./src/components/Glyphs/G-longdash.vue')['default']
    GM: typeof import('./src/components/Glyphs/G-M.vue')['default']
    GN: typeof import('./src/components/Glyphs/G-N.vue')['default']
    GO: typeof import('./src/components/Glyphs/G-O.vue')['default']
    GP: typeof import('./src/components/Glyphs/G-P.vue')['default']
    GQ: typeof import('./src/components/Glyphs/G-Q.vue')['default']
    GQuestion: typeof import('./src/components/Glyphs/G-question.vue')['default']
    GR: typeof import('./src/components/Glyphs/G-R.vue')['default']
    GS: typeof import('./src/components/Glyphs/G-S.vue')['default']
    GT: typeof import('./src/components/Glyphs/G-T.vue')['default']
    GU: typeof import('./src/components/Glyphs/G-U.vue')['default']
    GUmlautA: typeof import('./src/components/Glyphs/G-umlautA.vue')['default']
    GUmlautO: typeof import('./src/components/Glyphs/G-umlautO.vue')['default']
    GUmlautU: typeof import('./src/components/Glyphs/G-umlautU.vue')['default']
    GV: typeof import('./src/components/Glyphs/G-V.vue')['default']
    GY: typeof import('./src/components/Glyphs/G-Y.vue')['default']
    GZ: typeof import('./src/components/Glyphs/G-Z.vue')['default']
    GZeroconsonant: typeof import('./src/components/Glyphs/G-zeroconsonant.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NEight: typeof import('./src/components/Glyphs/N-eight.vue')['default']
    NEighty: typeof import('./src/components/Glyphs/N-eighty.vue')['default']
    NFive: typeof import('./src/components/Glyphs/N-five.vue')['default']
    NFivety: typeof import('./src/components/Glyphs/N-fivety.vue')['default']
    NFour: typeof import('./src/components/Glyphs/N-four.vue')['default']
    NFourty: typeof import('./src/components/Glyphs/N-fourty.vue')['default']
    NNine: typeof import('./src/components/Glyphs/N-nine.vue')['default']
    NNinety: typeof import('./src/components/Glyphs/N-ninety.vue')['default']
    NOne: typeof import('./src/components/Glyphs/N-one.vue')['default']
    NSeven: typeof import('./src/components/Glyphs/N-seven.vue')['default']
    NSeventy: typeof import('./src/components/Glyphs/N-seventy.vue')['default']
    NSix: typeof import('./src/components/Glyphs/N-six.vue')['default']
    NSixty: typeof import('./src/components/Glyphs/N-sixty.vue')['default']
    NTen: typeof import('./src/components/Glyphs/N-ten.vue')['default']
    NTherty: typeof import('./src/components/Glyphs/N-therty.vue')['default']
    NThree: typeof import('./src/components/Glyphs/N-three.vue')['default']
    NTwenty: typeof import('./src/components/Glyphs/N-twenty.vue')['default']
    NTwo: typeof import('./src/components/Glyphs/N-two.vue')['default']
    NZero: typeof import('./src/components/Glyphs/N-zero.vue')['default']
  }
}
