export{default as GlyphB}from "./G-B.vue";
export{default as GlyphcedillaC}from "./G-cedillaC.vue";
export{default as GlyphD}from "./G-D.vue";
export{default as GlyphE}from "./G-E.vue";
export{default as GlyphF}from "./G-F.vue";
export{default as GlyphG}from "./G-G.vue";
export{default as GlyphH}from "./G-H.vue";
export{default as GlyphI}from "./G-I.vue";
export{default as GlyphJ}from "./G-J.vue";
export{default as GlyphK}from "./G-K.vue";
export{default as GlyphL}from "./G-L.vue";
export{default as GlyphM}from "./G-M.vue";
export{default as GlyphN}from "./G-N.vue";
export{default as GlyphO}from "./G-O.vue";
export{default as GlyphP}from "./G-P.vue";
export{default as GlyphQ}from "./G-Q.vue";
export{default as GlyphR}from "./G-R.vue";
export{default as GlyphS}from "./G-S.vue";
export{default as GlyphcedillaS}from "./G-cedillaS.vue";
export{default as GlyphT}from "./G-T.vue";
export{default as GlyphU}from "./G-U.vue";
export{default as GlyphV}from "./G-V.vue";
export{default as GlyphY}from "./G-Y.vue";
export{default as GlyphZ}from "./G-Z.vue";
export{default as Glyphzeroconsonant}from "./G-zeroconsonant.vue";
export{default as GlyphumlautA}from "./G-umlautA.vue";
export{default as GlyphumlautO}from "./G-umlautO.vue";
export{default as GlyphumlautU}from "./G-umlautU.vue";
export{default as Glyphcomma}from "./G-comma.vue";
export{default as Glyphquestion}from "./G-question.vue";
export{default as Num0}from "./N-zero.vue" ;
export{default as Num1}from "./N-one.vue" ;
export{default as Num2}from "./N-two.vue" ;
export{default as Num3}from "./N-three.vue" ;
export{default as Num4}from "./N-four.vue" ;
export{default as Num5}from "./N-five.vue" ;
export{default as Num6}from "./N-six.vue" ;
export{default as Num7}from "./N-seven.vue" ;
export{default as Num8}from "./N-eight.vue" ;
export{default as Num9}from "./N-nine.vue" ;
export{default as Num10}from "./N-ten.vue" ;
export{default as Num20}from "./N-twenty.vue" ;
export{default as Num30}from "./N-therty.vue" ;
export{default as Num40}from "./N-fourty.vue" ;
export{default as Num50}from "./N-fivety.vue" ;
export{default as Num60}from "./N-sixty.vue" ;
export{default as Num70}from "./N-seventy.vue" ;
export{default as Num80}from "./N-eighty.vue" ;
export{default as Num90}from "./N-ninety.vue" ;